small changes done
SimonThormeyer/beuthSoundGroup pull request #232
Opened 2020-07-13 00:11 UTC by chanty1512

safari recorder new notification
fix menu position & background color

2020-07-14 13:26 UTC, MalteMittrowann requested changes
The loop and randomNotesAndDots button are gone....

![image](https://user-images.githubusercontent.com/43847487/87430598-bdc1d180-c5e5-11ea-998e-2699d990ec87.png)

Looping with the _space bar_ works though.

And I can do crazy shit now:

![image](https://user-images.githubusercontent.com/43847487/87432103-d6cb8200-c5e7-11ea-92b2-4f7b9b19f5d9.png)

-------------

The notification when recording while using Firefox is good.

2020-07-14 14:47 UTC, chanty1512 commented
also wegen den unteren menu icons: bei mir sind die da und du musst den canvas jetzt scrollen, weil die menu icons jetzt fest sind und an bottom vom canvas "geklebt" sind

2020-07-14 14:47 UTC, chanty1512 commented
und mit den ganzen loopsymbolen: das ging auch schon vorher. ich verstehe deine anmerkung nicht ?

2020-07-14 14:52 UTC, chanty1512 commented
ich habe jetzt nochmal den bereich für die loopicons verkleinert, sodass die loopicons nicht über den gesamten screen gehen

2020-07-15 11:57 UTC, chanty1512 commented
jetzt ist noch das zitat von terry riley auf dem startoverlay zu sehen

2020-07-15 21:25 UTC, MalteMittrowann approved these changes
Maybe the **helpdialogue** has to be readjusted after merging this PR:
No other bugs found created by this PR :-)

Thank you for these changes!

2020-07-15 21:26 UTC, merged